# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNUqddE5ARD8tNgQaHmJ-U2FMNjXlIA8

Met Office UK Radar Observations
=========================================================

The Met Office radar data is stored in .h5 files (HDF5 format — Hierarchical Data Format)
Think of an HDF5 file like a filing cabinet: it has groups (drawers) and datasets (folders inside drawers).

Bucket : s3://met-office-radar-obs-data  (eu-west-2)
Format : ODIM HDF5  (.h5)
Update : every 15 minutes
Docs   : https://www.metoffice.gov.uk/binaries/content/assets/metofficegovuk/
         pdf/business/data/external-data/asdi-radar-1km.pdf

Requirements
------------
    pip install boto3 s3fs h5py numpy matplotlib
"""

pip install boto3 s3fs h5py numpy matplotlib

"""## Exploring the File Structure

-  Open the file and explore what's inside it
"""

import h5py

file_path = "/content/drive/MyDrive/Dissertation/202411210930_ODIM_ng_radar_rainrate_composite_1km_UK.h5"  # ← change this


def explore_group(group, indent=0):
    """
    Recursively prints everything inside an HDF5 group.

    Parameters:
        group  : an h5py Group object (think: a folder)
        indent : how many spaces to indent (increases as we go deeper)
    """
    prefix = "  " * indent  # e.g. "    " at depth 2

    for key in group.keys():           # loop over everything in this group
        item = group[key]              # get the item by name

        if isinstance(item, h5py.Group):
            # It's a folder — print it, then recurse INTO it
            print(f"{prefix}📁 GROUP: {key}")
            explore_group(item, indent + 1)   # ← go one level deeper

        elif isinstance(item, h5py.Dataset):
            # It's actual data — print its name, shape, and type
            print(f"{prefix}📄 DATASET: {key}")
            print(f"{prefix}     shape : {item.shape}")
            print(f"{prefix}     dtype : {item.dtype}")

            # Also print any attributes attached to this dataset
            # Attributes are metadata — like labels on a jar
            if len(item.attrs) > 0:
                for attr_key, attr_val in item.attrs.items():
                    print(f"{prefix}     attr  → {attr_key}: {attr_val}")


# ── Open and explore ───────────────────────────────────────────────────────
# We open the file, do ALL our work inside the with block,
# and only close it at the end. No nested functions that might
# confuse the file handle.

with h5py.File(file_path, "r") as f:

    print("=== FILE STRUCTURE ===\n")
    explore_group(f)       # start at the root, indent=0

    # ── Root-level attributes ──────────────────────────────────────────────
    # The root "/" group often has file-level metadata attached to it
    print("\n=== ROOT ATTRIBUTES ===\n")
    if len(f.attrs) > 0:
        for key, val in f.attrs.items():
            print(f"  {key}: {val}")
    else:
        print("  (no root attributes found)")

"""The where, what, and how groups are standard ODIM metadata.

They tell you where the grid is, what the numbers mean, and how the data was collected.
"""

"""
202411210930_ODIM_ng_radar_rainrate_composite_1km_UK.h5
    │   │ │ │ └─ UK-wide composite
    │   │ │ └─── 1km resolution grid
    │   │ └───── rain RATE (mm/hour, not accumulation)
    │   └──────── 09:30 UTC
    └──────────── 21 November 2024


📁 dataset1          ← one "scan" / one moment in time
  📁 data1           ← the actual rainfall product
    📄 data          ← THE GRID: 2175 rows × 1725 columns of float32 values
    📁 what          ← metadata about THIS dataset (units, scale, nodata value)
  📁 how             ← HOW this scan was made (algorithm, etc.)
  📁 what            ← WHAT quantity this is (rain rate, timestamp)
📁 how               ← file-level "how"
📁 what              ← file-level "what" (date, time, source)
📁 where             ← WHERE geographically (grid origin, pixel size, projection)
"""


"""
dataset1/data1/data     :     The 2D rainfall grid — this IS the radar image
(2175, 1725)      :    2175 rows (North→South) × 1725 columns (West→East) covering the UK at 1km per pixel
where    :         Contains the grid's geographic coordinates so you can plot it on a map
what    :      Contains the timestamp, units, nodata/fill values
"""

"""## Reading the Metadata Properly"""

with h5py.File(file_path, "r") as f:

    # ── "what" groups tell you WHAT the numbers mean ───────────────────────
    # There are two: one at file level, one at dataset level.
    # We want both.

    print("=== FILE-LEVEL 'what' (date, time, source) ===\n")
    for key, val in f["what"].attrs.items():
        print(f"  {key}: {val}")

    print("\n=== DATASET-LEVEL 'what' (units, gain, offset, nodata) ===\n")
    for key, val in f["dataset1"]["what"].attrs.items():
        print(f"  {key}: {val}")

    print("\n=== 'where' (geographic grid info) ===\n")
    for key, val in f["where"].attrs.items():
        print(f"  {key}: {val}")

    print("\n=== dataset1/data1/what (per-array metadata) ===\n")
    for key, val in f["dataset1"]["data1"]["what"].attrs.items():
        print(f"  {key}: {val}")

"""The gain, offset, nodata, and undetect values in the what groups are essential — they tell you how to convert raw pixel values into actual mm/hour.

## Key Dataset Parameters

### File Identity
- **date / time**: Observation timestamp — `20241121` at `09:30:00 UTC` (21 November 2024, 9:30am)
- **object: COMP**: This is a *composite* — rainfall from all UK radar stations merged into one national image
- **source**: The 15 individual WMO radar stations that contributed to this composite
- **version: H5rad 2.2**: Follows the ODIM HDF5 v2.2 standard for European radar data exchange

### The Grid (`where`)
- **xsize / ysize**: The grid is **1725 columns × 2175 rows** — one pixel per km, covering the whole UK
- **xscale / yscale: 1000.0**: Each pixel represents a **1km × 1km** area on the ground
- **projdef**: The map projection used — **Transverse Mercator** (the same as British National Grid), centred on lon=-2, lat=49
- **LL/LR/UL/UR lat-lon**: The four corner coordinates of the grid — spanning roughly **43.7°N to 62.9°N** and **-18°W to 16°E**

### The Data Values (`dataset1/data1/what`)
- **quantity: RATE**: Each pixel value is an instantaneous **rainfall rate in mm/hour**
- **gain: 1.0**: No rescaling needed — raw values are already in mm/hour (gain of 1 means multiply by 1)
- **offset: 0.0**: No offset shift needed — formula is simply `real_value = (raw_value × gain) + offset`
- **nodata: -1.0**: Pixels with value `-1.0` mean **no data available** (e.g. outside radar coverage) — must be masked out before analysis
- **undetect: 0.0**: Pixels with value `0.0` mean the radar looked but detected **no rainfall** — genuinely dry areas

### Critical distinction
- `undetect (0.0)` = radar saw nothing → **dry**
- `nodata (-1.0)` = radar couldn't see there → **unknown** — treat differently in analysis

NOTE:

The single most important thing to remember going forward: always mask nodata = -1.0 before doing any calculations, otherwise your mean rainfall, max values etc. will be completely wrong.
"""

# ── CELL: Install pysteps ─────────────────────────────────────────────────
!pip install pysteps --quiet

# ── CELL: Load with pySTEPS — lets it handle all the projection maths ─────
from pysteps.io.importers import import_odim_hdf5
from pysteps.visualization.precipfields import plot_precip_field
import matplotlib.pyplot as plt
import numpy as np

file_path = "/content/drive/MyDrive/Dissertation/202411210930_ODIM_ng_radar_rainrate_composite_1km_UK.h5"

# import_odim_hdf5 returns three things:
#   rain_pysteps : the 2D rainfall array (mm/hr), already masked
#   quality      : a quality/confidence array (often None)
#   metadata     : a dictionary with ALL geographic and unit info resolved
#
# The key argument is qty="RATE" — tells it we want rain rate, not reflectivity

rain_pysteps, quality, metadata = import_odim_hdf5(file_path, qty="RATE")

# ── Inspect what pySTEPS extracted ────────────────────────────────────────
print("=== ARRAY ===")
print(f"  Shape      : {rain_pysteps.shape}")
print(f"  dtype      : {rain_pysteps.dtype}")
print(f"  Min        : {np.nanmin(rain_pysteps):.3f}")
print(f"  Max        : {np.nanmax(rain_pysteps):.3f}")

print("\n=== METADATA (everything pySTEPS resolved for us) ===")
for key, val in metadata.items():
    print(f"  {key:20s} : {val}")

# ── CELL: Plot with pySTEPS built-in visualiser ───────────────────────────
# plot_precip_field() knows about ODIM projections and handles
# the coordinate transform internally.
#
# geodata is the key — it's the geographic info pySTEPS extracted,
# telling the plotter exactly where each pixel sits.

fig, ax = plt.subplots(figsize=(10, 12))

plot_precip_field(
    rain_pysteps,
    geodata=metadata,        # ← this is what fixes the alignment
    units="mm/h",
    title="UK Rainfall Radar Composite\n21 November 2024  –  09:30 UTC",
    axis="on",
    ax=ax
)

plt.tight_layout()
plt.savefig("uk_radar_pysteps.png", dpi=150, bbox_inches="tight")
plt.show()

# ── Print the geodata so we can see what coords pySTEPS is using ──────────
print("\n=== GEODATA USED FOR PLOTTING ===")
print(f"  x1 (left)   : {metadata['x1']:,.0f} m")
print(f"  x2 (right)  : {metadata['x2']:,.0f} m")
print(f"  y1 (bottom) : {metadata['y1']:,.0f} m")
print(f"  y2 (top)    : {metadata['y2']:,.0f} m")
print(f"  projection  : {metadata['projection']}")
